name: CodeCov

on:
  push:
    branches: [ master ]

jobs:
  cd:
    name: CodeCov
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: 
          fetch-depth: 0

      - name: Coverage Badge
        uses: tj-actions/coverage-badge-py@v1.2

      - name: Verify Changed files
        uses: tj-actions/verify-changed-files@v6
        id: changed_files
        with:
          files: coverage.svg
